In [4]:
import pandas as pd
import numpy as np

In [5]:
credits= pd.read_csv("tmdb_5000_credits.csv")
ini=pd.read_csv('tmdb_5000_movies.csv')

In [6]:
ini.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [7]:
movies=ini.merge(credits,on='title')

In [8]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [10]:
#values to keep in data

movies=movies[['genres','title','keywords','overview','cast','crew','id']]

In [11]:
movies

,genres,title,keywords,overview,cast,crew,id
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529
...,...,...,...,...,...,...,...
4804,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",9367
4805,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",Newlyweds,[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",72766
4806,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","Signed, Sealed, Delivered","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",231617
4807,[],Shanghai Calling,[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",126186
4808,"[{""id"": 99, ""name"": ""Documentary""}]",My Date with Drew,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",25975

In [12]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4809 non-null   object
 1   title     4809 non-null   object
 2   keywords  4809 non-null   object
 3   overview  4806 non-null   object
 4   cast      4809 non-null   object
 5   crew      4809 non-null   object
 6   id        4809 non-null   int64
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [13]:
movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Length: 4809, dtype: bool

In [14]:
movies.isnull().sum()

movies.dropna(inplace=True)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\3259950529.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [15]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [16]:
import ast

In [17]:
def crew_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return (l)

In [18]:
movies['crew']=movies['crew'].apply(crew_director)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\3095203423.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(crew_director)

In [19]:
def process1(obj):
    y=[]
    j=0
    for i in ast.literal_eval(obj):
        if j!=3:
            y.append(i['name'])
            j=j+1
        else:
            break

    return(y)

In [20]:
def process2(obj):
    y=[]
    for i in ast.literal_eval(obj):
        y.append(i['name'])
    return (y)

In [21]:
movies['genres']=movies['genres'].apply(process2)
movies['cast']=movies['cast'].apply(process1)

#movies['keywords']=movies['keywords'].apply(process2)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\4018042942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(process2)
C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\4018042942.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(process1)

In [22]:
def crew_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i('job')==i('Director'):
            l.append(i['name'])
            break
    return (l)

In [23]:
movies['keywords']=movies['keywords'].apply(process2)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\4067641115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(process2)

In [24]:
movies.head(5)

,genres,title,keywords,overview,cast,crew,id
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],19995
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],285
2,"[Action, Adventure, Crime]",Spectre,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],206647
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],49026
4,"[Action, Adventure, Science Fiction]",John Carter,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],49529

In [25]:
movies['overview']=movies['overview'].apply(lambda x: x.split())

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\2156989849.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview']=movies['overview'].apply(lambda x: x.split())

In [26]:
movies['tags']=movies['overview']+movies['keywords']+movies['genres']+movies['cast']+movies['crew']

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\1431560438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['overview']+movies['keywords']+movies['genres']+movies['cast']+movies['crew']

In [27]:
def removeSpace(obj):
    y=[]
    for i in obj:
        y.append(i.replace(" ",""))
    return (y)

In [28]:
movies['cast']=movies['cast'].apply(removeSpace)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\1914331251.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(removeSpace)

In [29]:
movies['crew']=movies['crew'].apply(removeSpace)
movies['genres']=movies['genres'].apply(removeSpace)
movies['keywords']=movies['keywords'].apply(removeSpace)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\338689830.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(removeSpace)
C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\338689830.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(removeSpace)
C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\338689830.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(removeSpace)

In [30]:
movies.drop(columns=['overview','keywords','crew','cast','genres'],inplace=True)

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\3956094704.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.drop(columns=['overview','keywords','crew','cast','genres'],inplace=True)

In [31]:
movies['tags']=movies['tags'].apply(lambda x: " ".join(x))

C:\Users\Prithvij Tyagi\AppData\Local\Temp\ipykernel_21552\2587516724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(lambda x: " ".join(x))

In [32]:
from nltk import PorterStemmer
ps=PorterStemmer()

In [33]:
def steem(text):
    l=[]
    
    for i in text.split():
        l.append(ps.stem(i))

    return " ".join(i)

In [34]:
movies['tags'].apply(steem)

0             C a m e r o n
1         V e r b i n s k i
2               M e n d e s
3                 N o l a n
4             S t a n t o n
               ...
4804      R o d r i g u e z
4805              B u r n s
4806              S m i t h
4807                H s i a
4808    H e r z l i n g e r
Name: tags, Length: 4806, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
cv=CountVectorizer(max_features=5000, stop_words='english')
vec=cv.fit_transform(movies['tags']).toarray()

In [37]:
vec.shape

(4806, 5000)

In [38]:
similarity=cosine_similarity(vec)

In [39]:
similarity.shape

(4806, 4806)

In [40]:
sorted(list(enumerate(similarity[0])),reverse=True)

[(4805, np.float64(0.0)),
 (4804, np.float64(0.05345224838248487)),
 (4803, np.float64(0.03142696805273544)),
 (4802, np.float64(0.029814239699997188)),
 (4801, np.float64(0.014002800840280095)),
 (4800, np.float64(0.0)),
 (4799, np.float64(0.06666666666666667)),
 (4798, np.float64(0.013801311186847081)),
 (4797, np.float64(0.0)),
 (4796, np.float64(0.0)),
 (4795, np.float64(0.0)),
 (4794, np.float64(0.0)),
 (4793, np.float64(0.04082482904638629)),
 (4792, np.float64(0.0)),
 (4791, np.float64(0.016843038421330378)),
 (4790, np.float64(0.06467616667635545)),
 (4789, np.float64(0.06851887098275315)),
 (4788, np.float64(0.02309401076758503)),
 (4787, np.float64(0.015032920560056577)),
 (4786, np.float64(0.0)),
 (4785, np.float64(0.0)),
 (4784, np.float64(0.037463432463267755)),
 (4783, np.float64(0.0)),
 (4782, np.float64(0.039735970711951306)),
 (4781, np.float64(0.04020151261036848)),
 (4780, np.float64(0.015430334996209188)),
 (4779, np.float64(0.04364357804719846)),
 (4778, np.float64(0.0)),
 (4777, np.float64(0.059628479399994376)),
 (4776, np.float64(0.02309401076758503)),
 (4775, np.float64(0.017609018126512475)),
 (4774, np.float64(0.028867513459481284)),
 (4773, np.float64(0.018257418583505533)),
 (4772, np.float64(0.01702513061517497)),
 (4771, np.float64(0.050395263067896955)),
 (4770, np.float64(0.0)),
 (4769, np.float64(0.0)),
 (4768, np.float64(0.0)),
 (4767, np.float64(0.06793662204867573)),
 (4766, np.float64(0.035355339059327376)),
 (4765, np.float64(0.0)),
 (4764, np.float64(0.0)),
 (4763, np.float64(0.028867513459481284)),
 (4762, np.float64(0.008908708063747479)),
 (4761, np.float64(0.03521803625302495)),
 (4760, np.float64(0.0)),
 (4759, np.float64(0.01571348402636772)),
 (4758, np.float64(0.0)),
 (4757, np.float64(0.02800560168056019)),
 (4756, np.float64(0.0)),
 (4755, np.float64(0.014213381090374027)),
 (4754, np.float64(0.02108185106778919)),
 (4753, np.float64(0.0)),
 (4752, np.float64(0.06531972647421808)),
 (4751, np.float64(0.0)),
 (4750, np.float64(0.0)),
 (4749, np.float64(0.0)),
 (4748, np.float64(0.024759378423606912)),
 (4747, np.float64(0.0)),
 (4746, np.float64(0.0)),
 (4745, np.float64(0.0)),
 (4744, np.float64(0.04082482904638629)),
 (4743, np.float64(0.04595879916971408)),
 (4742, np.float64(0.02581988897471611)),
 (4741, np.float64(0.02182178902359923)),
 (4740, np.float64(0.017213259316477405)),
 (4739, np.float64(0.017213259316477405)),
 (4738, np.float64(0.0)),
 (4737, np.float64(0.07559289460184543)),
 (4736, np.float64(0.024077170617153837)),
 (4735, np.float64(0.012309149097933271)),
 (4734, np.float64(0.0)),
 (4733, np.float64(0.0)),
 (4732, np.float64(0.0)),
 (4731, np.float64(0.11239029738980327)),
 (4730, np.float64(0.017817416127494958)),
 (4729, np.float64(0.0)),
 (4728, np.float64(0.0)),
 (4727, np.float64(0.05619514869490164)),
 (4726, np.float64(0.0)),
 (4725, np.float64(0.02309401076758503)),
 (4724, np.float64(0.0)),
 (4723, np.float64(0.0)),
 (4722, np.float64(0.04026936331284146)),
 (4721, np.float64(0.033686076842660756)),
 (4720, np.float64(0.017213259316477405)),
 (4719, np.float64(0.0)),
 (4718, np.float64(0.06666666666666665)),
 (4717, np.float64(0.0)),
 (4716, np.float64(0.0)),
 (4715, np.float64(0.0)),
 (4714, np.float64(0.0)),
 (4713, np.float64(0.03521803625302495)),
 (4712, np.float64(0.0)),
 (4711, np.float64(0.01370377419655063)),
 (4710, np.float64(0.0)),
 (4709, np.float64(0.0)),
 (4708, np.float64(0.0)),
 (4707, np.float64(0.047894747207139966)),
 (4706, np.float64(0.03521803625302495)),
 (4705, np.float64(0.0)),
 (4704, np.float64(0.044353276257274366)),
 (4703, np.float64(0.0654653670707977)),
 (4702, np.float64(0.03698001308168194)),
 (4701, np.float64(0.0)),
 (4700, np.float64(0.02182178902359923)),
 (4699, np.float64(0.016843038421330378)),
 (4698, np.float64(0.0)),
 (4697, np.float64(0.02581988897471611)),
 (4696, np.float64(0.023570226039551584)),
 (4695, np.float64(0.05865884600854131)),
 (4694, np.float64(0.09258200997725513)),
 (4693, np.float64(0.02010075630518424)),
 (4692, np.float64(0.0)),
 (4691, np.float64(0.05163977794943221)),
 (4690, np.float64(0.016843038421330378)),
 (4689, np.float64(0.01571348402636772)),
 (4688, np.float64(0.05443310539518173)),
 (4687, np.float64(0.024077170617153837)),
 (4686, np.float64(0.0)),
 (4685, np.float64(0.020739033894608502)),
 (4684, np.float64(0.0)),
 (4683, np.float64(0.0)),
 (4682, np.float64(0.012598815766974239)),
 (4681, np.float64(0.0)),
 (4680, np.float64(0.04216370213557838)),
 (4679, np.float64(0.0)),
 (4678, np.float64(0.0563436169819011)),
 (4677, np.float64(0.0)),
 (4676, np.float64(0.0)),
 (4675, np.float64(0.06885303726590962)),
 (4674, np.float64(0.03405026123034994)),
 (4673, np.float64(0.08512565307587484)),
 (4672, np.float64(0.06189844605901728)),
 (4671, np.float64(0.018731716231633878)),
 (4670, np.float64(0.013801311186847081)),
 (4669, np.float64(0.018731716231633878)),
 (4668, np.float64(0.02309401076758503)),
 (4667, np.float64(0.04082482904638629)),
 (4666, np.float64(0.020739033894608502)),
 (4665, np.float64(0.0)),
 (4664, np.float64(0.14253932901995964)),
 (4663, np.float64(0.0)),
 (4662, np.float64(0.0)),
 (4661, np.float64(0.020739033894608502)),
 (4660, np.float64(0.0)),
 (4659, np.float64(0.023570226039551584)),
 (4658, np.float64(0.0)),
 (4657, np.float64(0.09128709291752767)),
 (4656, np.float64(0.04232073695151589)),
 (4655, np.float64(0.0)),
 (4654, np.float64(0.08888888888888888)),
 (4653, np.float64(0.0)),
 (4652, np.float64(0.02010075630518424)),
 (4651, np.float64(0.0)),
 (4650, np.float64(0.09128709291752767)),
 (4649, np.float64(0.03796631983009995)),
 (4648, np.float64(0.0)),
 (4647, np.float64(0.043301270189221926)),
 (4646, np.float64(0.024077170617153837)),
 (4645, np.float64(0.020739033894608502)),
 (4644, np.float64(0.0)),
 (4643, np.float64(0.04618802153517006)),
 (4642, np.float64(0.045291081365783824)),
 (4641, np.float64(0.05773502691896257)),
 (4640, np.float64(0.08421519210665189)),
 (4639, np.float64(0.0)),
 (4638, np.float64(0.061237243569579436)),
 (4637, np.float64(0.02800560168056019)),
 (4636, np.float64(0.08164965809277258)),
 (4635, np.float64(0.02649064714130087)),
 (4634, np.float64(0.028426762180748053)),
 (4633, np.float64(0.016666666666666666)),
 (4632, np.float64(0.02309401076758503)),
 (4631, np.float64(0.0)),
 (4630, np.float64(0.025503068522533524)),
 (4629, np.float64(0.019802950859533482)),
 (4628, np.float64(0.0)),
 (4627, np.float64(0.0)),
 (4626, np.float64(0.07213357077339458)),
 (4625, np.float64(0.0)),
 (4624, np.float64(0.03442651863295481)),
 (4623, np.float64(0.06963106238227913)),
 (4622, np.float64(0.0)),
 (4621, np.float64(0.0)),
 (4620, np.float64(0.05282705437953743)),
 (4619, np.float64(0.0)),
 (4618, np.float64(0.019802950859533482)),
 (4617, np.float64(0.0)),
 (4616, np.float64(0.0)),
 (4615, np.float64(0.0)),
 (4614, np.float64(0.0)),
 (4613, np.float64(0.01370377419655063)),
 (4612, np.float64(0.0)),
 (4611, np.float64(0.08576900278702357)),
 (4610, np.float64(0.0)),
 (4609, np.float64(0.0)),
 (4608, np.float64(0.024902912254587607)),
 (4607, np.float64(0.02800560168056019)),
 (4606, np.float64(0.0)),
 (4605, np.float64(0.0)),
 (4604, np.float64(0.04618802153517006)),
 (4603, np.float64(0.0)),
 (4602, np.float64(0.1044465935734187)),
 (4601, np.float64(0.0)),
 (4600, np.float64(0.09428090415820632)),
 (4599, np.float64(0.0)),
 (4598, np.float64(0.015569978883230457)),
 (4597, np.float64(0.07947194142390261)),
 (4596, np.float64(0.1811643254631353)),
 (4595, np.float64(0.0)),
 (4594, np.float64(0.02309401076758503)),
 (4593, np.float64(0.0)),
 (4592, np.float64(0.0)),
 (4591, np.float64(0.03903600291794132)),
 (4590, np.float64(0.045098761680169734)),
 (4589, np.float64(0.033686076842660756)),
 (4588, np.float64(0.0)),
 (4587, np.float64(0.07947194142390261)),
 (4586, np.float64(0.0)),
 (4585, np.float64(0.0)),
 (4584, np.float64(0.0)),
 (4583, np.float64(0.0)),
 (4582, np.float64(0.021350420507344946)),
 (4581, np.float64(0.0)),
 (4580, np.float64(0.0)),
 (4579, np.float64(0.0)),
 (4578, np.float64(0.0)),
 (4577, np.float64(0.0)),
 (4576, np.float64(0.039223227027636795)),
 (4575, np.float64(0.016843038421330378)),
 (4574, np.float64(0.0)),
 (4573, np.float64(0.018731716231633878)),
 (4572, np.float64(0.028867513459481284)),
 (4571, np.float64(0.0)),
 (4570, np.float64(0.018731716231633878)),
 (4569, np.float64(0.041478067789217005)),
 (4568, np.float64(0.06432675209026767)),
 (4567, np.float64(0.0)),
 (4566, np.float64(0.06467616667635545)),
 (4565, np.float64(0.010675210253672473)),
 (4564, np.float64(0.02581988897471611)),
 (4563, np.float64(0.0)),
 (4562, np.float64(0.0)),
 (4561, np.float64(0.03521803625302495)),
 (4560, np.float64(0.041478067789217005)),
 (4559, np.float64(0.02909571869813231)),
 (4558, np.float64(0.05819143739626462)),
 (4557, np.float64(0.024077170617153837)),
 (4556, np.float64(0.037463432463267755)),
 (4555, np.float64(0.07559289460184543)),
 (4554, np.float64(0.019802950859533482)),
 (4553, np.float64(0.01601281538050871)),
 (4552, np.float64(0.013900960937138315)),
 (4551, np.float64(0.0)),
 (4550, np.float64(0.0)),
 (4549, np.float64(0.019802950859533482)),
 (4548, np.float64(0.0)),
 (4547, np.float64(0.0)),
 (4546, np.float64(0.014784425419091455)),
 (4545, np.float64(0.15074151616205694)),
 (4544, np.float64(0.0)),
 (4543, np.float64(0.018731716231633878)),
 (4542, np.float64(0.02581988897471611)),
 (4541, np.float64(0.0)),
 (4540, np.float64(0.018731716231633878)),
 (4539, np.float64(0.0)),
 (4538, np.float64(0.06467616667635545)),
 (4537, np.float64(0.0)),
 (4536, np.float64(0.018033392693348645)),
 (4535, np.float64(0.042884501393511784)),
 (4534, np.float64(0.0)),
 (4533, np.float64(0.05601120336112038)),
 (4532, np.float64(0.01223980122724209)),
 (4531, np.float64(0.015430334996209188)),
 (4530, np.float64(0.01370377419655063)),
 (4529, np.float64(0.016169041669088863)),
 (4528, np.float64(0.029814239699997188)),
 (4527, np.float64(0.0)),
 (4526, np.float64(0.0)),
 (4525, np.float64(0.014784425419091455)),
 (4524, np.float64(0.0)),
 (4523, np.float64(0.016169041669088863)),
 (4522, np.float64(0.0)),
 (4521, np.float64(0.0)),
 (4520, np.float64(0.0)),
 (4519, np.float64(0.054100178080045934)),
 (4518, np.float64(0.011785113019775792)),
 (4517, np.float64(0.0)),
 (4516, np.float64(0.05163977794943222)),
 (4515, np.float64(0.0)),
 (4514, np.float64(0.04850712500726659)),
 (4513, np.float64(0.060647843486312254)),
 (4512, np.float64(0.10613372610104645)),
 (4511, np.float64(0.0)),
 (4510, np.float64(0.02780192187427663)),
 (4509, np.float64(0.0)),
 (4508, np.float64(0.0)),
 (4507, np.float64(0.0)),
 (4506, np.float64(0.04399413450640598)),
 (4505, np.float64(0.020739033894608502)),
 (4504, np.float64(0.0)),
 (4503, np.float64(0.0)),
 (4502, np.float64(0.05601120336112038)),
 (4501, np.float64(0.0)),
 (4500, np.float64(0.014664711502135327)),
 (4499, np.float64(0.0)),
 (4498, np.float64(0.016169041669088863)),
 (4497, np.float64(0.0)),
 (4496, np.float64(0.0)),
 (4495, np.float64(0.0)),
 (4494, np.float64(0.0)),
 (4493, np.float64(0.0)),
 (4492, np.float64(0.05163977794943222)),
 (4491, np.float64(0.0)),
 (4490, np.float64(0.0975900072948533)),
 (4489, np.float64(0.021535276082326617)),
 (4488, np.float64(0.0)),
 (4487, np.float64(0.0)),
 (4486, np.float64(0.0)),
 (4485, np.float64(0.08164965809277258)),
 (4484, np.float64(0.030065841120113155)),
 (4483, np.float64(0.024343224778007377)),
 (4482, np.float64(0.018731716231633878)),
 (4481, np.float64(0.0)),
 (4480, np.float64(0.0)),
 (4479, np.float64(0.0)),
 (4478, np.float64(0.0)),
 (4477, np.float64(0.0)),
 (4476, np.float64(0.020739033894608502)),
 (4475, np.float64(0.015861031714362882)),
 (4474, np.float64(0.0)),
 (4473, np.float64(0.11111111111111109)),
 (4472, np.float64(0.03698001308168194)),
 (4471, np.float64(0.035634832254989916)),
 (4470, np.float64(0.016843038421330378)),
 (4469, np.float64(0.03405026123034994)),
 (4468, np.float64(0.15491933384829665)),
 (4467, np.float64(0.0)),
 (4466, np.float64(0.02447960245448418)),
 (4465, np.float64(0.0)),
 (4464, np.float64(0.0)),
 (4463, np.float64(0.024618298195866542)),
 (4462, np.float64(0.0)),
 (4461, np.float64(0.0)),
 (4460, np.float64(0.04714045207910317)),
 (4459, np.float64(0.01849000654084097)),
 (4458, np.float64(0.01632993161855452)),
 (4457, np.float64(0.0)),
 (4456, np.float64(0.0)),
 (4455, np.float64(0.0)),
 (4454, np.float64(0.0)),
 (4453, np.float64(0.06885303726590962)),
 (4452, np.float64(0.017407765595569783)),
 (4451, np.float64(0.07784989441615228)),
 (4450, np.float64(0.0305887645160749)),
 (4449, np.float64(0.0)),
 (4448, np.float64(0.0)),
 (4447, np.float64(0.0)),
 (4446, np.float64(0.016666666666666666)),
 (4445, np.float64(0.0)),
 (4444, np.float64(0.021442250696755892)),
 (4443, np.float64(0.042884501393511784)),
 (4442, np.float64(0.0)),
 (4441, np.float64(0.0)),
 (4440, np.float64(0.0)),
 (4439, np.float64(0.0)),
 (4438, np.float64(0.0)),
 (4437, np.float64(0.0)),
 (4436, np.float64(0.0)),
 (4435, np.float64(0.0)),
 (4434, np.float64(0.018033392693348645)),
 (4433, np.float64(0.0)),
 (4432, np.float64(0.05481509678620252)),
 (4431, np.float64(0.07071067811865475)),
 (4430, np.float64(0.0)),
 (4429, np.float64(0.04200840252084029)),
 (4428, np.float64(0.0)),
 (4427, np.float64(0.028644594961577313)),
 (4426, np.float64(0.0)),
 (4425, np.float64(0.0)),
 (4424, np.float64(0.0)),
 (4423, np.float64(0.0)),
 (4422, np.float64(0.01849000654084097)),
 (4421, np.float64(0.04618802153517006)),
 (4420, np.float64(0.041478067789217005)),
 (4419, np.float64(0.0)),
 (4418, np.float64(0.0)),
 (4417, np.float64(0.023570226039551584)),
 (4416, np.float64(0.0)),
 (4415, np.float64(0.05443310539518173)),
 (4414, np.float64(0.0)),
 (4413, np.float64(0.01951800145897066)),
 (4412, np.float64(0.04216370213557838)),
 (4411, np.float64(0.023570226039551584)),
 (4410, np.float64(0.01632993161855452)),
 (4409, np.float64(0.0)),
 (4408, np.float64(0.019802950859533482)),
 (4407, np.float64(0.0)),
 (4406, np.float64(0.018257418583505533)),
 (4405, np.float64(0.1732050807568877)),
 (4404, np.float64(0.0)),
 (4403, np.float64(0.06793662204867573)),
 (4402, np.float64(0.03606678538669729)),
 (4401, np.float64(0.016495721976846445)),
 (4400, np.float64(0.048154341234307674)),
 (4399, np.float64(0.03202563076101742)),
 (4398, np.float64(0.06227991553292183)),
 (4397, np.float64(0.01370377419655063)),
 (4396, np.float64(0.018983159915049976)),
 (4395, np.float64(0.0)),
 (4394, np.float64(0.0)),
 (4393, np.float64(0.0)),
 (4392, np.float64(0.028426762180748053)),
 (4391, np.float64(0.06793662204867573)),
 (4390, np.float64(0.022645540682891912)),
 (4389, np.float64(0.0)),
 (4388, np.float64(0.050697940041958225)),
 (4387, np.float64(0.0)),
 (4386, np.float64(0.0)),
 (4385, np.float64(0.045291081365783824)),
 (4384, np.float64(0.05865884600854131)),
 (4383, np.float64(0.03405026123034994)),
 (4382, np.float64(0.02800560168056019)),
 (4381, np.float64(0.0)),
 (4380, np.float64(0.015430334996209188)),
 (4379, np.float64(0.0)),
 (4378, np.float64(0.0)),
 (4377, np.float64(0.031722063428725765)),
 (4376, np.float64(0.0)),
 (4375, np.float64(0.05601120336112038)),
 (4374, np.float64(0.0)),
 (4373, np.float64(0.02800560168056019)),
 (4372, np.float64(0.015569978883230457)),
 (4371, np.float64(0.02684624220856097)),
 (4370, np.float64(0.0)),
 (4369, np.float64(0.034815531191139566)),
 (4368, np.float64(0.09847319278346617)),
 (4367, np.float64(0.0)),
 (4366, np.float64(0.0)),
 (4365, np.float64(0.02649064714130087)),
 (4364, np.float64(0.0)),
 (4363, np.float64(0.0)),
 (4362, np.float64(0.024618298195866542)),
 (4361, np.float64(0.0)),
 (4360, np.float64(0.0)),
 (4359, np.float64(0.01924500897298752)),
 (4358, np.float64(0.01571348402636772)),
 (4357, np.float64(0.06324555320336757)),
 (4356, np.float64(0.0)),
 (4355, np.float64(0.08164965809277258)),
 (4354, np.float64(0.018257418583505533)),
 (4353, np.float64(0.1414213562373095)),
 (4352, np.float64(0.0)),
 (4351, np.float64(0.022645540682891912)),
 (4350, np.float64(0.012598815766974239)),
 (4349, np.float64(0.039605901719066965)),
 (4348, np.float64(0.10079052613579391)),
 (4347, np.float64(0.0)),
 (4346, np.float64(0.0)),
 (4345, np.float64(0.0)),
 (4344, np.float64(0.014664711502135327)),
 (4343, np.float64(0.16413890689295377)),
 (4342, np.float64(0.0)),
 (4341, np.float64(0.04898979485566356)),
 (4340, np.float64(0.013245323570650435)),
 (4339, np.float64(0.055470019622522904)),
 (4338, np.float64(0.0)),
 (4337, np.float64(0.015569978883230457)),
 (4336, np.float64(0.39207842352784267)),
 (4335, np.float64(0.017213259316477405)),
 (4334, np.float64(0.0)),
 (4333, np.float64(0.10596258856520348)),
 (4332, np.float64(0.02309401076758503)),
 (4331, np.float64(0.07698003589195009)),
 (4330, np.float64(0.024618298195866542)),
 (4329, np.float64(0.06963106238227913)),
 (4328, np.float64(0.0)),
 (4327, np.float64(0.01951800145897066)),
 (4326, np.float64(0.026318067798390753)),
 (4325, np.float64(0.0917662935482247)),
 (4324, np.float64(0.020412414523193145)),
 (4323, np.float64(0.0)),
 (4322, np.float64(0.0)),
 (4321, np.float64(0.0)),
 (4320, np.float64(0.04444444444444444)),
 (4319, np.float64(0.02309401076758503)),
 (4318, np.float64(0.0)),
 (4317, np.float64(0.017213259316477405)),
 (4316, np.float64(0.10801234497346432)),
 (4315, np.float64(0.0)),
 (4314, np.float64(0.02581988897471611)),
 (4313, np.float64(0.021442250696755892)),
 (4312, np.float64(0.05913770167636582)),
 (4311, np.float64(0.02309401076758503)),
 (4310, np.float64(0.0)),
 (4309, np.float64(0.0)),
 (4308, np.float64(0.0)),
 (4307, np.float64(0.0)),
 (4306, np.float64(0.05619514869490164)),
 (4305, np.float64(0.03872983346207416)),
 (4304, np.float64(0.0)),
 (4303, np.float64(0.0)),
 (4302, np.float64(0.0)),
 (4301, np.float64(0.0)),
 (4300, np.float64(0.024618298195866542)),
 (4299, np.float64(0.01571348402636772)),
 (4298, np.float64(0.0)),
 (4297, np.float64(0.0)),
 (4296, np.float64(0.0)),
 (4295, np.float64(0.017609018126512475)),
 (4294, np.float64(0.04444444444444444)),
 (4293, np.float64(0.034815531191139566)),
 (4292, np.float64(0.01849000654084097)),
 (4291, np.float64(0.0)),
 (4290, np.float64(0.04618802153517006)),
 (4289, np.float64(0.0)),
 (4288, np.float64(0.02780192187427663)),
 (4287, np.float64(0.0)),
 (4286, np.float64(0.0)),
 (4285, np.float64(0.017817416127494958)),
 (4284, np.float64(0.017213259316477405)),
 (4283, np.float64(0.0)),
 (4282, np.float64(0.02222222222222222)),
 (4281, np.float64(0.027216552697590865)),
 (4280, np.float64(0.07784989441615228)),
 (4279, np.float64(0.06666666666666667)),
 (4278, np.float64(0.0)),
 (4277, np.float64(0.07514691493021793)),
 (4276, np.float64(0.11202240672224076)),
 (4275, np.float64(0.01571348402636772)),
 (4274, np.float64(0.0)),
 (4273, np.float64(0.04216370213557838)),
 (4272, np.float64(0.0)),
 (4271, np.float64(0.05107539184552491)),
 (4270, np.float64(0.05)),
 (4269, np.float64(0.02108185106778919)),
 (4268, np.float64(0.05619514869490164)),
 (4267, np.float64(0.013159033899195377)),
 (4266, np.float64(0.041702882811414946)),
 (4265, np.float64(0.015032920560056577)),
 (4264, np.float64(0.0)),
 (4263, np.float64(0.016495721976846445)),
 (4262, np.float64(0.01529438225803745)),
 (4261, np.float64(0.05282705437953743)),
 (4260, np.float64(0.0)),
 (4259, np.float64(0.02800560168056019)),
 (4258, np.float64(0.0)),
 (4257, np.float64(0.0759326396601999)),
 (4256, np.float64(0.0)),
 (4255, np.float64(0.0)),
 (4254, np.float64(0.08295613557843401)),
 (4253, np.float64(0.0)),
 (4252, np.float64(0.0)),
 (4251, np.float64(0.024618298195866542)),
 (4250, np.float64(0.037796447300922714)),
 (4249, np.float64(0.012991396049232617)),
 (4248, np.float64(0.027216552697590865)),
 (4247, np.float64(0.08944271909999156)),
 (4246, np.float64(0.050395263067896955)),
 (4245, np.float64(0.02581988897471611)),
 (4244, np.float64(0.030860669992418377)),
 (4243, np.float64(0.0)),
 (4242, np.float64(0.0)),

In [52]:
def reccomend(film):
    mov_idx=movies[movies['title']==film].index[0]
    dist=similarity[mov_idx]
    l=sorted(list(enumerate(dist)),reverse=True,key=lambda x:x[1])[1:6]

    for i in l:
        print(movies.iloc[i[0]].title)

In [53]:
reccomend("Avatar")

Aliens
Moonraker
Alien
Alien³
Silent Running

In [42]:
import pickle

In [44]:

with open("movie_data.pkl", "wb") as f:
    pickle.dump(movies, f)
 #Have to convert movies to dict becoz pandas df cannot me sent 
#to different file

In [54]:
with open("similarity.pkl", "wb") as f:
    pickle.dump(similarity, f)